import '../js/preloader';
import '../js/sliders';
import '../js/language';
import '../js/scroll_animation';
import '../js/main_autopadding';
import '../js/scroll_to_block';
import '../js/burger_menu';
import '../js/tabs';
import '../js/sendmail';
